# Data merging

The previously preprocessed data from four different sources were merged into one data frame. To ensure all features were present per day, days where at least one parameter was missing were dropped.

In [1]:
import pandas as pd

In [2]:
hd = pd.read_csv('/Users/polzovatel/Desktop/Python/Portfolio/Diabetes/HealthAppData/HealthData.csv',
                 parse_dates=['Date'])

In [3]:
pr1 = pd.read_csv('/Users/polzovatel/Desktop/Python/Portfolio/Diabetes/PatientRecords/PatientRecords_DA.csv',
                 parse_dates=['Date'])

In [4]:
pr2 = pd.read_csv('/Users/polzovatel/Desktop/Python/Portfolio/Diabetes/PatientRecords/PatientRecords_E.csv',
                 parse_dates=['Date'])

In [5]:
wd = pd.read_csv('/Users/polzovatel/Desktop/Python/Portfolio/Diabetes/WeatherData/WeatherData.csv',
                parse_dates=['Date'])

In [6]:
df = pd.concat([pr1,pr2,hd,wd])

In [7]:
df

                     Date    DV   BG  shID  bID  SC  HR  Temp  Humid
0     2017-08-25 06:00:00  0.00  5.3   1.0  0.0 NaN NaN   NaN    NaN
1     2017-08-25 08:00:00  6.62  6.7   4.0  0.0 NaN NaN   NaN    NaN
2     2017-08-25 12:00:00  4.46  5.5   4.0  0.0 NaN NaN   NaN    NaN
3     2017-08-25 15:00:00  1.15  3.5   1.0  0.0 NaN NaN   NaN    NaN
4     2017-08-25 18:00:00  1.00  4.9   1.0  0.0 NaN NaN   NaN    NaN
...                   ...   ...  ...   ...  ...  ..  ..   ...    ...
26299 2021-12-31 19:00:00   NaN  NaN   NaN  NaN NaN NaN -25.2  63.06
26300 2021-12-31 20:00:00   NaN  NaN   NaN  NaN NaN NaN -25.0  69.27
26301 2021-12-31 21:00:00   NaN  NaN   NaN  NaN NaN NaN -24.0  76.22
26302 2021-12-31 22:00:00   NaN  NaN   NaN  NaN NaN NaN -23.0  69.98
26303 2021-12-31 23:00:00   NaN  NaN   NaN  NaN NaN NaN -22.0  63.85

[92041 rows x 9 columns]

In [8]:
#setting index to date
df = df.set_index('Date')
df = df.sort_index()

In [9]:
df

                       DV   BG  shID  bID     SC  HR  Temp  Humid
Date
2017-08-25 06:00:00  0.00  5.3   1.0  0.0    NaN NaN   NaN    NaN
2017-08-25 08:00:00  6.62  6.7   4.0  0.0    NaN NaN   NaN    NaN
2017-08-25 12:00:00  4.46  5.5   4.0  0.0    NaN NaN   NaN    NaN
2017-08-25 15:00:00  1.15  3.5   1.0  0.0    NaN NaN   NaN    NaN
2017-08-25 18:00:00  1.00  4.9   1.0  0.0    NaN NaN   NaN    NaN
...                   ...  ...   ...  ...    ...  ..   ...    ...
2022-10-19 09:09:51   NaN  NaN   NaN  NaN   16.0 NaN   NaN    NaN
2022-10-19 10:42:18   NaN  NaN   NaN  NaN    2.0 NaN   NaN    NaN
2022-10-19 10:58:40   NaN  NaN   NaN  NaN  611.0 NaN   NaN    NaN
2022-10-19 11:13:04   NaN  NaN   NaN  NaN  348.0 NaN   NaN    NaN
2022-10-19 11:23:04   NaN  NaN   NaN  NaN   39.0 NaN   NaN    NaN

[92041 rows x 8 columns]

In [10]:
#create a list of unique dates
unique_dates = df.index.map(lambda i: str(i.date())).unique()
unique_dates

Index(['2017-08-25', '2017-08-26', '2017-08-27', '2017-08-28', '2017-08-29',
       '2017-08-30', '2017-08-31', '2017-10-02', '2017-10-03', '2017-10-04',
       ...
       '2022-10-10', '2022-10-11', '2022-10-12', '2022-10-13', '2022-10-14',
       '2022-10-15', '2022-10-16', '2022-10-17', '2022-10-18', '2022-10-19'],
      dtype='object', name='Date', length=1475)

In [11]:
#check if there is any column with missing values per unique date
#create a list of dates to drop
to_drop_dates = []  

for i in unique_dates:
    for c in df.columns:
        if df.loc[i,c].isna().sum() == len(df.loc[i]):
            to_drop_dates.extend(df.loc[i].index.tolist())
            break
to_drop_dates

[Timestamp('2017-08-25 06:00:00'),
 Timestamp('2017-08-25 08:00:00'),
 Timestamp('2017-08-25 12:00:00'),
 Timestamp('2017-08-25 15:00:00'),
 Timestamp('2017-08-25 18:00:00'),
 Timestamp('2017-08-25 19:00:00'),
 Timestamp('2017-08-25 22:00:00'),
 Timestamp('2017-08-26 07:00:00'),
 Timestamp('2017-08-26 08:00:00'),
 Timestamp('2017-08-26 11:00:00'),
 Timestamp('2017-08-26 13:00:00'),
 Timestamp('2017-08-26 17:00:00'),
 Timestamp('2017-08-26 19:00:00'),
 Timestamp('2017-08-26 22:00:00'),
 Timestamp('2017-08-26 23:00:00'),
 Timestamp('2017-08-27 07:00:00'),
 Timestamp('2017-08-27 08:00:00'),
 Timestamp('2017-08-27 11:00:00'),
 Timestamp('2017-08-27 19:00:00'),
 Timestamp('2017-08-27 22:00:00'),
 Timestamp('2017-08-28 07:00:00'),
 Timestamp('2017-08-28 12:00:00'),
 Timestamp('2017-08-28 16:00:00'),
 Timestamp('2017-08-28 19:00:00'),
 Timestamp('2017-08-28 22:00:00'),
 Timestamp('2017-08-29 06:00:00'),
 Timestamp('2017-08-29 07:30:00'),
 Timestamp('2017-08-29 10:00:00'),
 Timestamp('2017-08-29 12:00:00'),
 Timestamp('2017-08-29 14:30:00'),
 Timestamp('2017-08-29 17:00:00'),
 Timestamp('2017-08-29 19:30:00'),
 Timestamp('2017-08-29 22:00:00'),
 Timestamp('2017-08-30 07:00:00'),
 Timestamp('2017-08-30 08:00:00'),
 Timestamp('2017-08-30 12:00:00'),
 Timestamp('2017-08-30 15:00:00'),
 Timestamp('2017-08-30 17:00:00'),
 Timestamp('2017-08-30 19:00:00'),
 Timestamp('2017-08-30 22:00:00'),
 Timestamp('2017-08-31 07:00:00'),
 Timestamp('2017-08-31 12:00:00'),
 Timestamp('2017-08-31 15:00:00'),
 Timestamp('2017-08-31 19:00:00'),
 Timestamp('2017-08-31 22:00:00'),
 Timestamp('2017-10-02 08:00:00'),
 Timestamp('2017-10-02 12:00:00'),
 Timestamp('2017-10-02 15:20:00'),
 Timestamp('2017-10-02 18:00:00'),
 Timestamp('2017-10-02 19:30:00'),
 Timestamp('2017-10-02 21:30:00'),
 Timestamp('2017-10-03 07:00:00'),
 Timestamp('2017-10-03 11:00:00'),
 Timestamp('2017-10-03 12:00:00'),
 Timestamp('2017-10-03 15:00:00'),
 Timestamp('2017-10-03 18:00:00'),
 Timestamp('2017-10-03 22:00:00'),
 Timestamp('2017-10-04 07:00:00'),
 Timestamp('2017-10-04 11:00:00'),
 Timestamp('2017-10-04 15:30:00'),
 Timestamp('2017-10-04 18:00:00'),
 Timestamp('2017-10-04 22:00:00'),
 Timestamp('2017-10-05 07:00:00'),
 Timestamp('2017-10-05 08:00:00'),
 Timestamp('2017-10-05 12:00:00'),
 Timestamp('2017-10-05 15:30:00'),
 Timestamp('2017-10-05 18:00:00'),
 Timestamp('2017-10-05 19:30:00'),
 Timestamp('2017-10-05 22:00:00'),
 Timestamp('2017-10-06 07:00:00'),
 Timestamp('2017-10-06 08:00:00'),
 Timestamp('2017-10-06 12:00:00'),
 Timestamp('2017-10-06 13:30:00'),
 Timestamp('2017-10-06 17:00:00'),
 Timestamp('2017-10-06 19:30:00'),
 Timestamp('2017-10-06 22:00:00'),
 Timestamp('2017-10-07 05:03:00'),
 Timestamp('2017-10-07 08:00:00'),
 Timestamp('2017-10-07 11:30:00'),
 Timestamp('2017-10-07 14:00:00'),
 Timestamp('2017-10-07 17:00:00'),
 Timestamp('2017-10-07 18:00:00'),
 Timestamp('2017-10-07 22:00:00'),
 Timestamp('2017-10-08 08:00:00'),
 Timestamp('2017-10-08 09:00:00'),
 Timestamp('2017-10-08 12:00:00'),
 Timestamp('2017-10-08 14:00:00'),
 Timestamp('2017-10-08 17:00:00'),
 Timestamp('2017-10-08 19:30:00'),
 Timestamp('2017-10-08 22:00:00'),
 Timestamp('2017-10-09 04:03:00'),
 Timestamp('2017-10-09 06:00:00'),
 Timestamp('2017-10-09 07:30:00'),
 Timestamp('2017-10-09 11:00:00'),
 Timestamp('2017-10-09 12:00:00'),
 Timestamp('2017-10-09 15:00:00'),
 Timestamp('2017-10-09 20:00:00'),
 Timestamp('2017-10-09 22:00:00'),
 Timestamp('2017-10-10 08:00:00'),
 Timestamp('2017-10-10 09:00:00'),
 Timestamp('2017-10-10 12:00:00'),
 Timestamp('2017-10-10 13:00:00'),
 Timestamp('2017-10-10 15:00:00'),
 Timestamp('2017-10-10 17:00:00'),
 Timestamp('2017-10-10 19:30:00'),
 Timestamp('2017-10-10 21:00:00'),
 Timestamp('2017-10-10 22:00:00'),
 Timestamp('2017-10-11 07:00:00'),
 Timestamp('2017-10-11 11:00:00'),
 Timestamp('2017-10-11 15:30:00'),
 Timestamp('2017-10-11 20:00:00'),
 Timestamp('2017-10-11 22:00:00'),
 Timestamp('2017-10-13 09:00:00'),
 Timestamp('2017-10-13 12:00:00'),
 Timestamp('2017-10-13 15:00:00'),
 Timestamp('2017-10-13 17:00:00'),
 Timestamp('2017-10-13 20:30:00'),
 Timestamp('2017-10-13 22:00:00'),
 Timestamp('2017-10-14 07:00:00'),
 Timestamp('2017-10-14 09:00:00'),
 Timestamp('2017-10-14 13:00:00'),
 Timestamp('2017-10-14 17:00:00'),
 Timestamp('2017-10-14 19:30:00'),
 Timestamp('2017-10-14 21:30:00'),
 Timestamp('2017-10-14 23:30:00'),
 Timestamp('2017-10-15 07:00:00'),
 Timestamp('2017-10-15 09:03:00'),
 Timestamp('2017-10-24 04:00:00'),
 Timestamp('2017-10-24 06:00:00'),
 Timestamp('2018-06-13 15:55:00'),
 Timestamp('2018-06-24 07:00:00'),
 Timestamp('2018-06-24 08:00:00'),
 Timestamp('2018-10-28 20:53:44'),
 Timestamp('2018-10-28 21:25:37'),
 Timestamp('2018-10-28 22:16:19'),
 Timestamp('2018-10-28 22:16:31'),
 Timestamp('2018-10-29 07:32:13'),
 Timestamp('2018-10-29 08:47:16'),
 Timestamp('2018-10-29 12:27:14'),
 Timestamp('2018-10-29 12:55:38'),
 Timestamp('2018-10-29 12:56:10'),
 Timestamp('2018-10-29 12:58:15'),
 Timestamp('2018-10-29 12:59:14'),
 Timestamp('2018-10-29 13:00:13'),
 Timestamp('2018-10-29 13:01:12'),
 Timestamp('2018-10-29 13:02:11'),
 Timestamp('2018-10-29 13:03:10'),
 Timestamp('2018-10-29 13:04:09'),
 Timestamp('2018-10-29 13:05:26'),
 Timestamp('2018-10-29 13:26:18'),
 Timestamp('2018-10-29 13:27:17'),
 Timestamp('2018-10-29 13:28:16'),
 Timestamp('2018-10-29 13:30:17'),
 Timestamp('2018-10-29 13:31:18'),
 Timestamp('2018-10-29 13:32:17'),
 Timestamp('2018-10-29 13:33:16'),
 Timestamp('2018-10-29 13:44:42'),
 Timestamp('2018-10-29 13:52:15'),
 Timestamp('2018-10-29 13:59:25'),
 Timestamp('2018-10-29 14:49:57'),
 Timestamp('2018-10-29 14:52:38'),
 Timestamp('2018-10-29 14:53:37'),
 Timestamp('2018-10-29 14:55:12'),
 Timestamp('2018-10-29 14:56:11'),
 Timestamp('2018-10-29 15:21:52'),
 Timestamp('2018-10-29 15:23:40'),
 Timestamp('2018-10-29 15:25:56'),
 Timestamp('2018-10-29 15:27:05'),
 Timestamp('2018-10-29 15:38:25'),
 Timestamp('2018-10-29 15:53:22'),
 Timestamp('2018-10-29 16:31:32'),
 Timestamp('2018-10-29 16:33:43'),
 Timestamp('2018-10-29 16:44:34'),
 Timestamp('2018-10-29 16:45:49'),
 Timestamp('2018-10-29 16:48:28'),
 Timestamp('2018-10-29 16:58:30'),
 Timestamp('2018-10-29 17:00:41'),
 Timestamp('2018-10-29 17:01:43'),
 Timestamp('2018-10-29 17:02:42'),
 Timestamp('2018-10-29 17:08:12'),
 Timestamp('2018-10-29 17:29:42'),
 Timestamp('2018-10-29 17:30:41'),
 Timestamp('2018-10-29 17:31:40'),
 Timestamp('2018-10-29 17:32:39'),
 Timestamp('2018-10-29 17:33:38'),
 Timestamp('2018-10-29 17:43:47'),
 Timestamp('2018-10-30 10:39:46'),
 Timestamp('2018-10-30 10:40:52'),
 Timestamp('2018-10-30 10:42:38'),
 Timestamp('2018-10-30 10:43:37'),
 Timestamp('2018-10-30 10:44:35'),
 Timestamp('2018-10-30 10:45:34'),
 Timestamp('2018-10-30 10:46:33'),
 Timestamp('2018-10-30 10:47:32'),
 Timestamp('2018-10-30 10:48:31'),
 Timestamp('2018-10-30 10:49:30'),
 Timestamp('2018-10-30 10:50:29'),
 Timestamp('2018-10-30 10:51:33'),
 Timestamp('2018-10-30 10:52:44'),
 Timestamp('2018-10-30 10:55:26'),
 Timestamp('2018-10-30 10:56:25'),
 Timestamp('2018-10-30 10:57:24'),
 Timestamp('2018-10-30 10:58:33'),
 Timestamp('2018-10-30 10:59:32'),
 Timestamp('2018-10-30 11:00:31'),
 Timestamp('2018-10-30 11:01:30'),
 Timestamp('2018-10-30 11:02:29'),
 Timestamp('2018-10-30 11:03:28'),
 Timestamp('2018-10-30 11:04:29'),
 Timestamp('2018-10-30 11:05:30'),
 Timestamp('2018-10-30 11:06:31'),
 Timestamp('2018-10-30 11:07:30'),
 Timestamp('2018-10-30 11:08:29'),
 Timestamp('2018-10-30 11:09:28'),
 Timestamp('2018-10-30 11:10:32'),
 Timestamp('2018-10-30 11:11:31'),
 Timestamp('2018-10-30 11:12:30'),
 Timestamp('2018-10-30 11:21:00'),
 Timestamp('2018-10-30 11:23:08'),
 Timestamp('2018-10-30 11:24:40'),
 Timestamp('2018-10-30 13:00:17'),
 Timestamp('2018-10-30 13:01:49'),
 Timestamp('2018-10-30 13:03:21'),
 Timestamp('2018-10-30 13:05:17'),
 Timestamp('2018-10-30 13:18:31'),
 Timestamp('2018-10-30 13:20:58'),
 Timestamp('2018-10-30 13:21:57'),
 Timestamp('2018-10-30 13:22:56'),
 Timestamp('2018-10-30 13:24:10'),
 Timestamp('2018-10-30 13:27:58'),
 Timestamp('2018-10-30 13:29:18'),
 Timestamp('2018-10-30 13:30:16'),
 Timestamp('2018-10-30 13:40:19'),
 Timestamp('2018-10-30 14:05:39'),
 Timestamp('2018-10-30 15:17:22'),
 Timestamp('2018-10-30 15:20:37'),
 Timestamp('2018-10-30 15:21:59'),
 Timestamp('2018-10-30 15:22:58'),
 Timestamp('2018-10-30 15:37:07'),
 Timestamp('2018-10-30 15:50:50'),
 Timestamp('2018-10-30 15:51:57'),
 Timestamp('2018-10-30 16:20:53'),
 Timestamp('2018-10-30 16:42:04'),
 Timestamp('2018-10-30 16:52:12'),
 Timestamp('2018-10-30 17:16:49'),
 Timestamp('2018-10-30 17:17:53'),
 Timestamp('2018-10-30 17:18:52'),
 Timestamp('2018-10-30 17:19:51'),
 Timestamp('2018-10-30 17:20:50'),
 Timestamp('2018-10-30 17:21:49'),
 Timestamp('2018-10-30 17:22:48'),
 Timestamp('2018-10-30 17:23:47'),
 Timestamp('2018-10-30 17:24:48'),
 Timestamp('2018-10-30 17:25:49'),
 Timestamp('2018-10-30 17:26:51'),
 Timestamp('2018-10-30 17:28:02'),
 Timestamp('2018-10-30 17:29:01'),
 Timestamp('2018-10-30 17:30:08'),
 Timestamp('2018-10-30 17:31:14'),
 Timestamp('2018-10-31 08:36:28'),
 Timestamp('2018-10-31 09:36:06'),
 Timestamp('2018-10-31 09:41:09'),
 Timestamp('2018-10-31 09:46:06'),
 Timestamp('2018-10-31 09:51:09'),
 Timestamp('2018-10-31 09:58:45'),
 Timestamp('2018-10-31 10:08:48'),
 Timestamp('2018-10-31 10:10:50'),
 Timestamp('2018-10-31 10:19:06'),
 Timestamp('2018-10-31 10:41:29'),
 Timestamp('2018-10-31 10:58:15'),
 Timestamp('2018-10-31 11:20:31'),
 Timestamp('2018-10-31 11:23:15'),
 Timestamp('2018-10-31 11:24:32'),
 Timestamp('2018-10-31 11:26:09'),
 Timestamp('2018-10-31 11:29:11'),
 Timestamp('2018-10-31 11:30:38'),
 Timestamp('2018-10-31 11:31:48'),
 Timestamp('2018-10-31 11:32:47'),
 Timestamp('2018-10-31 11:44:50'),
 Timestamp('2018-10-31 11:46:50'),
 Timestamp('2018-10-31 11:48:07'),
 Timestamp('2018-10-31 11:48:13'),
 Timestamp('2018-10-31 11:49:06'),
 Timestamp('2018-10-31 11:50:05'),
 Timestamp('2018-10-31 11:52:11'),
 Timestamp('2018-10-31 11:58:59'),
 Timestamp('2018-10-31 12:07:54'),
 Timestamp('2018-10-31 12:07:57'),
 Timestamp('2018-10-31 12:09:42'),
 Timestamp('2018-10-31 13:04:37'),
 Timestamp('2018-10-31 13:07:34'),
 Timestamp('2018-10-31 13:08:53'),
 Timestamp('2018-10-31 13:08:55'),
 Timestamp('2018-10-31 13:10:31'),
 Timestamp('2018-10-31 13:25:15'),
 Timestamp('2018-10-31 13:25:31'),
 Timestamp('2018-10-31 13:26:14'),
 Timestamp('2018-10-31 13:27:13'),
 Timestamp('2018-10-31 13:28:12'),
 Timestamp('2018-10-31 13:32:29'),
 Timestamp('2018-10-31 13:36:11'),
 Timestamp('2018-10-31 13:57:52'),
 Timestamp('2018-10-31 14:19:19'),
 Timestamp('2018-10-31 14:49:37'),
 Timestamp('2018-10-31 14:57:04'),
 Timestamp('2018-10-31 14:58:03'),
 Timestamp('2018-10-31 14:59:53'),
 Timestamp('2018-10-31 15:00:11'),
 Timestamp('2018-10-31 15:01:15'),
 Timestamp('2018-10-31 15:02:24'),
 Timestamp('2018-10-31 15:05:08'),
 Timestamp('2018-10-31 15:06:12'),
 Timestamp('2018-10-31 15:07:11'),
 Timestamp('2018-10-31 15:08:10'),
 Timestamp('2018-10-31 15:14:38'),
 Timestamp('2018-10-31 15:14:38'),
 Timestamp('2018-10-31 15:17:32'),
 Timestamp('2018-10-31 15:19:22'),
 Timestamp('2018-10-31 15:20:31'),
 Timestamp('2018-10-31 15:21:35'),
 Timestamp('2018-10-31 15:25:33'),
 Timestamp('2018-10-31 15:50:54'),
 Timestamp('2018-10-31 15:55:46'),
 Timestamp('2018-10-31 15:56:58'),
 Timestamp('2018-10-31 15:57:25'),
 Timestamp('2018-10-31 15:57:57'),
 Timestamp('2018-10-31 15:58:56'),
 Timestamp('2018-10-31 16:03:00'),
 Timestamp('2018-10-31 16:14:47'),
 Timestamp('2018-10-31 16:16:17'),
 Timestamp('2018-10-31 16:19:17'),
 Timestamp('2018-10-31 16:20:34'),
 Timestamp('2018-10-31 16:21:22'),
 Timestamp('2018-10-31 16:21:58'),
 Timestamp('2018-10-31 16:22:57'),
 Timestamp('2018-10-31 16:23:56'),
 Timestamp('2018-10-31 16:24:55'),
 Timestamp('2018-10-31 16:25:54'),
 Timestamp('2018-10-31 16:26:53'),
 Timestamp('2018-10-31 16:27:52'),
 Timestamp('2018-10-31 16:28:51'),
 Timestamp('2018-10-31 16:29:50'),
 Timestamp('2018-10-31 16:30:49'),
 Timestamp('2018-10-31 16:31:22'),
 Timestamp('2018-10-31 16:31:48'),
 Timestamp('2018-10-31 16:32:49'),
 Timestamp('2018-10-31 16:33:50'),
 Timestamp('2018-10-31 16:34:52'),
 Timestamp('2018-10-31 16:35:55'),
 Timestamp('2018-10-31 16:36:54'),
 Timestamp('2018-10-31 17:10:55'),
 Timestamp('2018-10-31 17:11:59'),
 Timestamp('2018-10-31 17:13:37'),
 Timestamp('2018-10-31 17:13:40'),
 Timestamp('2018-10-31 17:16:28'),
 Timestamp('2018-10-31 17:18:52'),
 Timestamp('2018-10-31 17:20:19'),
 Timestamp('2018-10-31 17:21:18'),
 Timestamp('2018-10-31 17:22:56'),
 Timestamp('2018-10-31 17:24:23'),
 Timestamp('2018-10-31 17:24:24'),
 Timestamp('2018-10-31 17:25:29'),
 Timestamp('2018-10-31 17:26:28'),
 Timestamp('2018-10-31 17:27:53'),
 Timestamp('2018-10-31 17:28:52'),
 Timestamp('2018-10-31 17:29:51'),
 Timestamp('2018-10-31 17:30:50'),
 Timestamp('2018-10-31 17:31:49'),
 Timestamp('2018-10-31 17:32:48'),
 Timestamp('2018-10-31 17:34:28'),
 Timestamp('2018-10-31 17:34:37'),
 Timestamp('2018-10-31 17:35:27'),
 Timestamp('2018-10-31 17:36:33'),
 Timestamp('2018-10-31 17:37:32'),
 Timestamp('2018-10-31 17:38:31'),
 Timestamp('2018-10-31 17:39:30'),
 Timestamp('2018-10-31 17:40:29'),
 Timestamp('2018-10-31 17:42:04'),
 Timestamp('2018-10-31 17:43:03'),
 Timestamp('2018-10-31 17:44:44'),
 Timestamp('2018-10-31 17:45:09'),
 Timestamp('2018-10-31 17:46:08'),
 Timestamp('2018-10-31 17:47:12'),
 Timestamp('2018-10-31 17:48:13'),
 Timestamp('2018-10-31 17:49:33'),
 Timestamp('2018-10-31 17:50:55'),
 Timestamp('2018-10-31 17:51:54'),
 Timestamp('2018-10-31 17:55:32'),
 Timestamp('2018-10-31 18:28:08'),
 Timestamp('2018-10-31 20:28:26'),
 Timestamp('2018-11-01 07:57:57'),
 Timestamp('2018-11-01 09:01:50'),
 Timestamp('2018-11-01 09:02:49'),
 Timestamp('2018-11-01 09:03:50'),
 Timestamp('2018-11-01 09:04:49'),
 Timestamp('2018-11-01 09:08:03'),
 Timestamp('2018-11-01 13:07:43'),
 Timestamp('2018-11-01 13:08:49'),
 Timestamp('2018-11-01 13:10:01'),
 Timestamp('2018-11-01 13:10:02'),
 Timestamp('2018-11-01 13:11:23'),
 Timestamp('2018-11-01 13:12:22'),
 Timestamp('2018-11-01 13:14:12'),
 Timestamp('2018-11-01 13:15:11'),
 Timestamp('2018-11-01 13:16:10'),
 Timestamp('2018-11-01 13:17:09'),
 Timestamp('2018-11-01 13:18:08'),
 Timestamp('2018-11-01 13:19:07'),
 Timestamp('2018-11-01 13:20:02'),
 Timestamp('2018-11-01 13:20:08'),
 Timestamp('2018-11-01 13:21:09'),
 Timestamp('2018-11-01 13:22:34'),
 Timestamp('2018-11-01 13:25:33'),
 Timestamp('2018-11-01 13:37:05'),
 Timestamp('2018-11-01 13:37:22'),
 Timestamp('2018-11-01 13:38:04'),
 Timestamp('2018-11-01 13:39:03'),
 Timestamp('2018-11-01 13:41:21'),
 Timestamp('2018-11-01 14:11:56'),
 Timestamp('2018-11-01 14:19:23'),
 Timestamp('2018-11-01 14:20:35'),
 Timestamp('2018-11-01 14:21:36'),
 Timestamp('2018-11-01 14:26:57'),
 Timestamp('2018-11-01 14:31:47'),
 Timestamp('2018-11-01 14:38:22'),
 Timestamp('2018-11-01 15:16:11'),
 Timestamp('2018-11-01 15:21:50'),
 Timestamp('2018-11-01 15:21:53'),
 Timestamp('2018-11-01 15:24:36'),
 Timestamp('2018-11-01 15:41:27'),
 Timestamp('2018-11-01 15:47:03'),
 Timestamp('2018-11-01 15:56:50'),
 Timestamp('2018-11-01 15:56:51'),
 Timestamp('2018-11-01 16:00:07'),
 Timestamp('2018-11-01 16:01:06'),
 Timestamp('2018-11-01 16:03:02'),
 Timestamp('2018-11-01 16:05:00'),
 Timestamp('2018-11-01 16:06:52'),
 Timestamp('2018-11-01 16:06:55'),
 Timestamp('2018-11-01 16:08:17'),
 Timestamp('2018-11-01 16:09:37'),
 Timestamp('2018-11-01 16:10:36'),
 Timestamp('2018-11-01 16:13:30'),
 Timestamp('2018-11-01 16:14:29'),
 Timestamp('2018-11-01 16:15:36'),
 Timestamp('2018-11-01 16:17:16'),
 Timestamp('2018-11-01 16:18:25'),
 Timestamp('2018-11-01 16:29:34'),
 Timestamp('2018-11-01 16:57:26'),
 Timestamp('2018-11-01 17:01:25'),
 Timestamp('2018-11-01 17:04:42'),
 Timestamp('2018-11-01 17:04:49'),
 Timestamp('2018-11-01 17:05:41'),
 Timestamp('2018-11-01 17:07:31'),
 Timestamp('2018-11-01 17:08:30'),
 Timestamp('2018-11-01 17:09:40'),
 Timestamp('2018-11-01 17:12:31'),
 Timestamp('2018-11-01 17:26:50'),
 Timestamp('2018-11-01 17:32:20'),
 Timestamp('2018-11-01 17:32:26'),
 Timestamp('2018-11-01 17:33:25'),
 Timestamp('2018-11-01 17:34:27'),
 Timestamp('2018-11-01 17:35:44'),
 Timestamp('2018-11-01 17:36:43'),
 Timestamp('2018-11-01 17:37:42'),
 Timestamp('2018-11-01 17:38:41'),
 Timestamp('2018-11-01 17:39:40'),
 Timestamp('2018-11-01 17:40:39'),
 Timestamp('2018-11-01 17:41:38'),
 Timestamp('2018-11-01 17:42:19'),
 Timestamp('2018-11-01 17:42:37'),
 Timestamp('2018-11-01 18:25:05'),
 Timestamp('2018-11-01 18:35:05'),
 Timestamp('2018-11-01 18:45:19'),
 Timestamp('2018-11-01 21:41:26'),
 Timestamp('2018-11-02 07:51:38'),
 Timestamp('2018-11-02 09:28:48'),
 Timestamp('2018-11-02 09:29:47'),
 Timestamp('2018-11-02 09:32:18'),
 Timestamp('2018-11-02 09:32:22'),
 Timestamp('2018-11-02 09:33:40'),
 Timestamp('2018-11-02 09:34:39'),
 Timestamp('2018-11-02 09:35:38'),
 Timestamp('2018-11-02 09:36:37'),
 Timestamp('2018-11-02 09:37:36'),
 Timestamp('2018-11-02 09:38:35'),
 Timestamp('2018-11-02 09:39:34'),
 Timestamp('2018-11-02 09:40:33'),
 Timestamp('2018-11-02 09:41:34'),
 Timestamp('2018-11-02 09:42:56'),
 Timestamp('2018-11-02 09:42:58'),
 Timestamp('2018-11-02 09:43:57'),
 Timestamp('2018-11-02 09:55:35'),
 Timestamp('2018-11-02 09:59:39'),
 Timestamp('2018-11-02 09:59:41'),
 Timestamp('2018-11-02 10:00:40'),
 Timestamp('2018-11-02 10:01:44'),
 Timestamp('2018-11-02 10:02:53'),
 Timestamp('2018-11-02 10:06:05'),
 Timestamp('2018-11-02 10:12:04'),
 Timestamp('2018-11-02 10:16:23'),
 Timestamp('2018-11-02 10:18:06'),
 Timestamp('2018-11-02 10:20:26'),
 Timestamp('2018-11-02 10:32:35'),
 Timestamp('2018-11-02 10:34:49'),
 Timestamp('2018-11-02 10:42:12'),
 Timestamp('2018-11-02 10:52:18'),
 Timestamp('2018-11-02 10:54:05'),
 Timestamp('2018-11-02 10:57:58'),
 Timestamp('2018-11-02 10:58:57'),
 Timestamp('2018-11-02 10:59:56'),
 Timestamp('2018-11-02 11:00:55'),
 Timestamp('2018-11-02 11:01:54'),
 Timestamp('2018-11-02 11:02:19'),
 Timestamp('2018-11-02 11:02:53'),
 Timestamp('2018-11-02 11:03:52'),
 Timestamp('2018-11-02 11:04:51'),
 Timestamp('2018-11-02 11:10:27'),
 Timestamp('2018-11-02 11:11:49'),
 Timestamp('2018-11-02 11:12:20'),
 Timestamp('2018-11-02 11:12:48'),
 Timestamp('2018-11-02 11:13:47'),
 Timestamp('2018-11-02 11:14:46'),
 Timestamp('2018-11-02 11:15:45'),
 Timestamp('2018-11-02 11:16:49'),
 Timestamp('2018-11-02 11:17:50'),
 Timestamp('2018-11-02 11:18:52'),
 Timestamp('2018-11-02 11:24:43'),
 Timestamp('2018-11-02 11:25:23'),
 Timestamp('2018-11-02 11:25:42'),
 Timestamp('2018-11-02 11:26:41'),
 Timestamp('2018-11-02 11:40:37'),
 Timestamp('2018-11-02 11:40:39'),
 Timestamp('2018-11-02 11:42:19'),
 Timestamp('2018-11-02 11:45:39'),
 Timestamp('2018-11-02 11:46:38'),
 Timestamp('2018-11-02 11:49:19'),
 Timestamp('2018-11-02 11:51:07'),
 Timestamp('2018-11-02 11:56:51'),
 Timestamp('2018-11-02 11:58:56'),
 Timestamp('2018-11-02 12:03:38'),
 Timestamp('2018-11-02 12:05:35'),
 Timestamp('2018-11-02 12:19:55'),
 Timestamp('2018-11-02 12:20:00'),
 Timestamp('2018-11-02 12:22:03'),
 Timestamp('2018-11-02 12:23:48'),
 Timestamp('2018-11-02 12:36:13'),
 Timestamp('2018-11-02 13:13:30'),
 Timestamp('2018-11-02 13:15:18'),
 Timestamp('2018-11-02 13:15:21'),
 Timestamp('2018-11-02 13:16:40'),
 Timestamp('2018-11-02 13:29:14'),
 Timestamp('2018-11-02 13:30:01'),
 Timestamp('2018-11-02 13:30:13'),
 Timestamp('2018-11-02 13:31:12'),
 Timestamp('2018-11-02 13:37:21'),
 Timestamp('2018-11-02 13:49:22'),
 Timestamp('2018-11-02 13:56:58'),
 Timestamp('2018-11-02 14:01:32'),
 Timestamp('2018-11-02 14:14:45'),
 Timestamp('2018-11-02 14:25:11'),
 Timestamp('2018-11-02 14:27:24'),
 Timestamp('2018-11-02 14:28:31'),
 Timestamp('2018-11-02 14:29:58'),
 Timestamp('2018-11-02 14:31:12'),
 Timestamp('2018-11-02 14:32:16'),
 Timestamp('2018-11-02 14:34:55'),
 Timestamp('2018-11-02 14:34:57'),
 Timestamp('2018-11-02 14:35:54'),
 Timestamp('2018-11-02 14:36:53'),
 Timestamp('2018-11-02 14:40:06'),

In [12]:
#dropping dates with missing values
df.drop(index=to_drop_dates,inplace=True)

In [13]:
df

                      DV   BG  shID  bID  SC  HR  Temp  Humid
Date
2019-01-08 00:00:00  NaN  NaN   NaN  NaN NaN NaN -17.0  59.64
2019-01-08 01:00:00  NaN  NaN   NaN  NaN NaN NaN -19.3  71.06
2019-01-08 02:00:00  NaN  NaN   NaN  NaN NaN NaN -17.0  65.13
2019-01-08 03:00:00  NaN  NaN   NaN  NaN NaN NaN -17.0  59.64
2019-01-08 03:30:00  0.0  3.7   0.0  2.0 NaN NaN   NaN    NaN
...                  ...  ...   ...  ...  ..  ..   ...    ...
2021-06-23 21:00:00  NaN  NaN   NaN  NaN NaN NaN  21.0  60.23
2021-06-23 22:00:00  0.0  0.0   0.0  0.0 NaN NaN   NaN    NaN
2021-06-23 22:00:00  0.0  0.0   0.0  0.0 NaN NaN   NaN    NaN
2021-06-23 22:00:00  NaN  NaN   NaN  NaN NaN NaN  20.2  58.80
2021-06-23 23:00:00  NaN  NaN   NaN  NaN NaN NaN  22.0  49.66

[25907 rows x 8 columns]

In [14]:
#reordering data frame
df = df[['bID','BG','DV','shID','SC','HR','Temp','Humid']]

In [15]:
df

                     bID   BG   DV  shID  SC  HR  Temp  Humid
Date
2019-01-08 00:00:00  NaN  NaN  NaN   NaN NaN NaN -17.0  59.64
2019-01-08 01:00:00  NaN  NaN  NaN   NaN NaN NaN -19.3  71.06
2019-01-08 02:00:00  NaN  NaN  NaN   NaN NaN NaN -17.0  65.13
2019-01-08 03:00:00  NaN  NaN  NaN   NaN NaN NaN -17.0  59.64
2019-01-08 03:30:00  2.0  3.7  0.0   0.0 NaN NaN   NaN    NaN
...                  ...  ...  ...   ...  ..  ..   ...    ...
2021-06-23 21:00:00  NaN  NaN  NaN   NaN NaN NaN  21.0  60.23
2021-06-23 22:00:00  0.0  0.0  0.0   0.0 NaN NaN   NaN    NaN
2021-06-23 22:00:00  0.0  0.0  0.0   0.0 NaN NaN   NaN    NaN
2021-06-23 22:00:00  NaN  NaN  NaN   NaN NaN NaN  20.2  58.80
2021-06-23 23:00:00  NaN  NaN  NaN   NaN NaN NaN  22.0  49.66

[25907 rows x 8 columns]

In [16]:
df.to_csv('FullData.csv')